version: '3.3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace:cached

    command: tail -f /var/log/pm2.log

    networks:
      - intranet

  redis:
    image: bitnami/redis:7.0
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - intranet

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/etc/mongo
    networks:
      - intranet

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - intranet

  kafka:
    image: bitnami/kafka:3.2.3
    networks:
      - intranet
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
    volumes:
      # This is where smtp4dev stores the database..
        - smtp4dev-data:/smtp4dev
    networks:
      - intranet

volumes:
  mongodb-data:
  smtp4dev-data:

networks:
  intranet:
